### ISSUE TITLE
Cyrilic read/write

### ISSUE THREAD

**Issue by shorban** [br-automation-com/PvJson#1]
When using WSTRING wariables with Cyrilic text, it writes as binary symbols. And if using UTF-8 Cyrilic text in file, PLC go to SERVICE mode.
Tested in X20CP1585 AR D4.52 and PvJson v4.73 CGI 6.3.0

**Comment by JobFranken** [comment]
I could reproduce the behavior with a small test project in simulation.

**Comment by alex-gimenez** [comment]
Hello @shorban , I just uploaded a new revision of the library that fixes this issue. Could you test it and give some feedback please?

Regards,
Alejandro
