### ISSUE TITLE
Json string in UTF-8

### ISSUE THREAD

**Issue by hpaldan** [br-automation-com/PvJson#15]
Hello!

Is it possible to get the Json string converted from ASCII to UTF-8 somehow?
I am trying to use PvJson to send data to the cloud and it can only interpret text in UTF-8.
I get that you can get single UTF characters but how do you turn the entire JSON output into UTF-8?

**Comment by hpaldan** [comment]
Never mind, seems like the problem wasn't the BR functions after all.

**Comment by priesf** [comment]
Hi, thanks for sharing. Nice job to solve it on your own. 
Assuming you used the conversion functions from the AsHTTP library (?) 
Maybe you can just shortly post what solved the problem for you? 

BR Fabian

**Comment by hpaldan** [comment]
Yes of course!
It was a bit of a mystery to figure out what datatype the jsonbuffer was pointing to, when trying to get the string length with strlen I got no error since the input data was a UDINT pointer but the simulaton environment wouldn't work. It went better with wcslen and wcscpy so I'm guessing it is pointing to a WSTRING datatype, or some other string datatype generated by a C/C++ program perhaps.

The problem wasn't the datatype of what the jsonbuffer pointer is pointing to however but the place I was sending the json string to was converting it to a string which added things like '\n' for newline and \ before the " sign. So I don't think there is anything I could do in the PLC to solve this.

**Comment by priesf** [comment]
Thanks for sharing.
