### ISSUE TITLE
Support for Automation Studio 6

### ISSUE THREAD

**Issue by lgiulio77** [br-automation-com/PvJson#16]
Library is not supported in Automation Studio 6. Must be rebuilt with new system:
![image](https://github.com/user-attachments/assets/5e90793f-773c-4f1d-829f-c29a68ac82b0)

**Comment by priesf** [comment]
At the moment nothing is scheduled. Will check who has time to convert and build it.

**Comment by FlatTony** [comment]
+1 Looking for the upgrade.

**Comment by mrcsrt94** [comment]
+1 looking for an upgrade too or to get sources for rebuild 
Thanks

**Comment by JobFranken** [comment]
Linked is a As6.0 build. Its not extensively tested. Please check if everything functions that u used in AS4 and report it back. 

We are in the background slowly working to make the source public but the original version uses multiple internal functions which makes it harder to make it buildable for everyone. 

https://github.com/br-automation-com/PvJson/releases/download/Rev/PvJson.V6.0.7001.zip
